# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a8a2147ea80ff04d1fe725cd228a4c0ba59eedef3e1f5c21584c7339921224669b6a4e6b2dceecd9f89faf78e7e5e25a8df7b3a287ec86f297efa498560ef97

test:
  secret_key_base: 1e272d5d75d4b3c06a690866b52067ccdaa874502203f4b1230a175ebf2c690afa47166473dc94c17f33f2fb2b7846c582f29bb5b53c58f9d1e89c64ca150a2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
